<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%countries}}`.
 */
class m250216_175610_create_countries_table extends Migration
{
    public $countries = [
        [
            'country_code' => 'JO',
            'name_en' => 'Jordan',
            'name_ar' => 'الأردن',
            'nationality_en' => 'Jordanian',
            'nationality_ar' => 'أردني',
        ],
        [
            'country_code' => 'AF',
            'name_en' => 'Afghanistan',
            'name_ar' => 'أفغانستان',
            'nationality_en' => 'Afghan',
            'nationality_ar' => 'أفغانستاني',
        ],
        [
            'country_code' => 'AL',
            'name_en' => 'Albania',
            'name_ar' => 'ألبانيا',
            'nationality_en' => 'Albanian',
            'nationality_ar' => 'ألباني',
        ],
        [
            'country_code' => 'AX',
            'name_en' => 'Aland Islands',
            'name_ar' => 'جزر آلاند',
            'nationality_en' => 'Aland Islander',
            'nationality_ar' => 'آلاندي',
        ],
        [
            'country_code' => 'DZ',
            'name_en' => 'Algeria',
            'name_ar' => 'الجزائر',
            'nationality_en' => 'Algerian',
            'nationality_ar' => 'جزائري',
        ],
        [
            'country_code' => 'AS',
            'name_en' => 'American Samoa',
            'name_ar' => 'ساموا-الأمريكي',
            'nationality_en' => 'American Samoan',
            'nationality_ar' => 'أمريكي سامواني',
        ],
        [
            'country_code' => 'AD',
            'name_en' => 'Andorra',
            'name_ar' => 'أندورا',
            'nationality_en' => 'Andorran',
            'nationality_ar' => 'أندوري',
        ],
        [
            'country_code' => 'AO',
            'name_en' => 'Angola',
            'name_ar' => 'أنغولا',
            'nationality_en' => 'Angolan',
            'nationality_ar' => 'أنقولي',
        ],
        [
            'country_code' => 'AI',
            'name_en' => 'Anguilla',
            'name_ar' => 'أنغويلا',
            'nationality_en' => 'Anguillan',
            'nationality_ar' => 'أنغويلي',
        ],
        [
            'country_code' => 'AQ',
            'name_en' => 'Antarctica',
            'name_ar' => 'أنتاركتيكا',
            'nationality_en' => 'Antarctican',
            'nationality_ar' => 'أنتاركتيكي',
        ],
        [
            'country_code' => 'AG',
            'name_en' => 'Antigua and Barbuda',
            'name_ar' => 'أنتيغوا وبربودا',
            'nationality_en' => 'Antiguan',
            'nationality_ar' => 'بربودي',
        ],
        [
            'country_code' => 'AR',
            'name_en' => 'Argentina',
            'name_ar' => 'الأرجنتين',
            'nationality_en' => 'Argentinian',
            'nationality_ar' => 'أرجنتيني',
        ],
        [
            'country_code' => 'AM',
            'name_en' => 'Armenia',
            'name_ar' => 'أرمينيا',
            'nationality_en' => 'Armenian',
            'nationality_ar' => 'أرميني',
        ],
        [
            'country_code' => 'AW',
            'name_en' => 'Aruba',
            'name_ar' => 'أروبه',
            'nationality_en' => 'Aruban',
            'nationality_ar' => 'أوروبهيني',
        ],
        [
            'country_code' => 'AU',
            'name_en' => 'Australia',
            'name_ar' => 'أستراليا',
            'nationality_en' => 'Australian',
            'nationality_ar' => 'أسترالي',
        ],
        [
            'country_code' => 'AT',
            'name_en' => 'Austria',
            'name_ar' => 'النمسا',
            'nationality_en' => 'Austrian',
            'nationality_ar' => 'نمساوي',
        ],
        [
            'country_code' => 'AZ',
            'name_en' => 'Azerbaijan',
            'name_ar' => 'أذربيجان',
            'nationality_en' => 'Azerbaijani',
            'nationality_ar' => 'أذربيجاني',
        ],
        [
            'country_code' => 'BS',
            'name_en' => 'Bahamas',
            'name_ar' => 'الباهاماس',
            'nationality_en' => 'Bahamian',
            'nationality_ar' => 'باهاميسي',
        ],
        [
            'country_code' => 'BH',
            'name_en' => 'Bahrain',
            'name_ar' => 'البحرين',
            'nationality_en' => 'Bahraini',
            'nationality_ar' => 'بحريني',
        ],
        [
            'country_code' => 'BD',
            'name_en' => 'Bangladesh',
            'name_ar' => 'بنغلاديش',
            'nationality_en' => 'Bangladeshi',
            'nationality_ar' => 'بنغلاديشي',
        ],
        [
            'country_code' => 'BB',
            'name_en' => 'Barbados',
            'name_ar' => 'بربادوس',
            'nationality_en' => 'Barbadian',
            'nationality_ar' => 'بربادوسي',
        ],
        [
            'country_code' => 'BY',
            'name_en' => 'Belarus',
            'name_ar' => 'روسيا البيضاء',
            'nationality_en' => 'Belarusian',
            'nationality_ar' => 'روسي',
        ],
        [
            'country_code' => 'BE',
            'name_en' => 'Belgium',
            'name_ar' => 'بلجيكا',
            'nationality_en' => 'Belgian',
            'nationality_ar' => 'بلجيكي',
        ],
        [
            'country_code' => 'BZ',
            'name_en' => 'Belize',
            'name_ar' => 'بيليز',
            'nationality_en' => 'Belizean',
            'nationality_ar' => 'بيليزي',
        ],
        [
            'country_code' => 'BJ',
            'name_en' => 'Benin',
            'name_ar' => 'بنين',
            'nationality_en' => 'Beninese',
            'nationality_ar' => 'بنيني',
        ],
        [
            'country_code' => 'BL',
            'name_en' => 'Saint Barthelemy',
            'name_ar' => 'سان بارتيلمي',
            'nationality_en' => 'Saint Barthelmian',
            'nationality_ar' => 'سان بارتيلمي',
        ],
        [
            'country_code' => 'BM',
            'name_en' => 'Bermuda',
            'name_ar' => 'جزر برمودا',
            'nationality_en' => 'Bermudan',
            'nationality_ar' => 'برمودي',
        ],
        [
            'country_code' => 'BT',
            'name_en' => 'Bhutan',
            'name_ar' => 'بوتان',
            'nationality_en' => 'Bhutanese',
            'nationality_ar' => 'بوتاني',
        ],
        [
            'country_code' => 'BO',
            'name_en' => 'Bolivia',
            'name_ar' => 'بوليفيا',
            'nationality_en' => 'Bolivian',
            'nationality_ar' => 'بوليفي',
        ],
        [
            'country_code' => 'BA',
            'name_en' => 'Bosnia and Herzegovina',
            'name_ar' => 'البوسنة و الهرسك',
            'nationality_en' => 'Bosnian / Herzegovinian',
            'nationality_ar' => 'بوسني/هرسكي',
        ],
        [
            'country_code' => 'BW',
            'name_en' => 'Botswana',
            'name_ar' => 'بوتسوانا',
            'nationality_en' => 'Botswanan',
            'nationality_ar' => 'بوتسواني',
        ],
        [
            'country_code' => 'BV',
            'name_en' => 'Bouvet Island',
            'name_ar' => 'جزيرة بوفيه',
            'nationality_en' => 'Bouvetian',
            'nationality_ar' => 'بوفيهي',
        ],
        [
            'country_code' => 'BR',
            'name_en' => 'Brazil',
            'name_ar' => 'البرازيل',
            'nationality_en' => 'Brazilian',
            'nationality_ar' => 'برازيلي',
        ],
        [
            'country_code' => 'IO',
            'name_en' => 'British Indian Ocean Territory',
            'name_ar' => 'إقليم المحيط الهندي البريطاني',
            'nationality_en' => 'British Indian Ocean Territory',
            'nationality_ar' => 'إقليم المحيط الهندي البريطاني',
        ],
        [
            'country_code' => 'BN',
            'name_en' => 'Brunei Darussalam',
            'name_ar' => 'بروني',
            'nationality_en' => 'Bruneian',
            'nationality_ar' => 'بروني',
        ],
        [
            'country_code' => 'BG',
            'name_en' => 'Bulgaria',
            'name_ar' => 'بلغاريا',
            'nationality_en' => 'Bulgarian',
            'nationality_ar' => 'بلغاري',
        ],
        [
            'country_code' => 'BF',
            'name_en' => 'Burkina Faso',
            'name_ar' => 'بوركينا فاسو',
            'nationality_en' => 'Burkinabe',
            'nationality_ar' => 'بوركيني',
        ],
        [
            'country_code' => 'BI',
            'name_en' => 'Burundi',
            'name_ar' => 'بوروندي',
            'nationality_en' => 'Burundian',
            'nationality_ar' => 'بورونيدي',
        ],
        [
            'country_code' => 'KH',
            'name_en' => 'Cambodia',
            'name_ar' => 'كمبوديا',
            'nationality_en' => 'Cambodian',
            'nationality_ar' => 'كمبودي',
        ],
        [
            'country_code' => 'CM',
            'name_en' => 'Cameroon',
            'name_ar' => 'كاميرون',
            'nationality_en' => 'Cameroonian',
            'nationality_ar' => 'كاميروني',
        ],
        [
            'country_code' => 'CA',
            'name_en' => 'Canada',
            'name_ar' => 'كندا',
            'nationality_en' => 'Canadian',
            'nationality_ar' => 'كندي',
        ],
        [
            'country_code' => 'CV',
            'name_en' => 'Cape Verde',
            'name_ar' => 'الرأس الأخضر',
            'nationality_en' => 'Cape Verdean',
            'nationality_ar' => 'الرأس الأخضر',
        ],
        [
            'country_code' => 'KY',
            'name_en' => 'Cayman Islands',
            'name_ar' => 'جزر كايمان',
            'nationality_en' => 'Caymanian',
            'nationality_ar' => 'كايماني',
        ],
        [
            'country_code' => 'CF',
            'name_en' => 'Central African Republic',
            'name_ar' => 'جمهورية أفريقيا الوسطى',
            'nationality_en' => 'Central African',
            'nationality_ar' => 'أفريقي',
        ],
        [
            'country_code' => 'TD',
            'name_en' => 'Chad',
            'name_ar' => 'تشاد',
            'nationality_en' => 'Chadian',
            'nationality_ar' => 'تشادي',
        ],
        [
            'country_code' => 'CL',
            'name_en' => 'Chile',
            'name_ar' => 'شيلي',
            'nationality_en' => 'Chilean',
            'nationality_ar' => 'شيلي',
        ],
        [
            'country_code' => 'CN',
            'name_en' => 'China',
            'name_ar' => 'الصين',
            'nationality_en' => 'Chinese',
            'nationality_ar' => 'صيني',
        ],
        [
            'country_code' => 'CX',
            'name_en' => 'Christmas Island',
            'name_ar' => 'جزيرة عيد الميلاد',
            'nationality_en' => 'Christmas Islander',
            'nationality_ar' => 'جزيرة عيد الميلاد',
        ],
        [
            'country_code' => 'CC',
            'name_en' => 'Cocos (Keeling) Islands',
            'name_ar' => 'جزر كوكوس',
            'nationality_en' => 'Cocos Islander',
            'nationality_ar' => 'جزر كوكوس',
        ],
        [
            'country_code' => 'CO',
            'name_en' => 'Colombia',
            'name_ar' => 'كولومبيا',
            'nationality_en' => 'Colombian',
            'nationality_ar' => 'كولومبي',
        ],
        [
            'country_code' => 'KM',
            'name_en' => 'Comoros',
            'name_ar' => 'جزر القمر',
            'nationality_en' => 'Comorian',
            'nationality_ar' => 'جزر القمر',
        ],
        [
            'country_code' => 'CG',
            'name_en' => 'Congo',
            'name_ar' => 'الكونغو',
            'nationality_en' => 'Congolese',
            'nationality_ar' => 'كونغي',
        ],
        [
            'country_code' => 'CK',
            'name_en' => 'Cook Islands',
            'name_ar' => 'جزر كوك',
            'nationality_en' => 'Cook Islander',
            'nationality_ar' => 'جزر كوك',
        ],
        [
            'country_code' => 'CR',
            'name_en' => 'Costa Rica',
            'name_ar' => 'كوستاريكا',
            'nationality_en' => 'Costa Rican',
            'nationality_ar' => 'كوستاريكي',
        ],
        [
            'country_code' => 'HR',
            'name_en' => 'Croatia',
            'name_ar' => 'كرواتيا',
            'nationality_en' => 'Croatian',
            'nationality_ar' => 'كوراتي',
        ],
        [
            'country_code' => 'CU',
            'name_en' => 'Cuba',
            'name_ar' => 'كوبا',
            'nationality_en' => 'Cuban',
            'nationality_ar' => 'كوبي',
        ],
        [
            'country_code' => 'CY',
            'name_en' => 'Cyprus',
            'name_ar' => 'قبرص',
            'nationality_en' => 'Cypriot',
            'nationality_ar' => 'قبرصي',
        ],
        [
            'country_code' => 'CW',
            'name_en' => 'Curaçao',
            'name_ar' => 'كوراساو',
            'nationality_en' => 'Curacian',
            'nationality_ar' => 'كوراساوي',
        ],
        [
            'country_code' => 'CZ',
            'name_en' => 'Czech Republic',
            'name_ar' => 'الجمهورية التشيكية',
            'nationality_en' => 'Czech',
            'nationality_ar' => 'تشيكي',
        ],
        [
            'country_code' => 'DK',
            'name_en' => 'Denmark',
            'name_ar' => 'الدانمارك',
            'nationality_en' => 'Danish',
            'nationality_ar' => 'دنماركي',
        ],
        [
            'country_code' => 'DJ',
            'name_en' => 'Djibouti',
            'name_ar' => 'جيبوتي',
            'nationality_en' => 'Djiboutian',
            'nationality_ar' => 'جيبوتي',
        ],
        [
            'country_code' => 'DM',
            'name_en' => 'Dominica',
            'name_ar' => 'دومينيكا',
            'nationality_en' => 'Dominican',
            'nationality_ar' => 'دومينيكي',
        ],
        [
            'country_code' => 'DO',
            'name_en' => 'Dominican Republic',
            'name_ar' => 'الجمهورية الدومينيكية',
            'nationality_en' => 'Dominican',
            'nationality_ar' => 'دومينيكي',
        ],
        [
            'country_code' => 'EC',
            'name_en' => 'Ecuador',
            'name_ar' => 'إكوادور',
            'nationality_en' => 'Ecuadorian',
            'nationality_ar' => 'إكوادوري',
        ],
        [
            'country_code' => 'EG',
            'name_en' => 'Egypt',
            'name_ar' => 'مصر',
            'nationality_en' => 'Egyptian',
            'nationality_ar' => 'مصري',
        ],
        [
            'country_code' => 'SV',
            'name_en' => 'El Salvador',
            'name_ar' => 'إلسلفادور',
            'nationality_en' => 'Salvadoran',
            'nationality_ar' => 'سلفادوري',
        ],
        [
            'country_code' => 'GQ',
            'name_en' => 'Equatorial Guinea',
            'name_ar' => 'غينيا الاستوائي',
            'nationality_en' => 'Equatorial Guinean',
            'nationality_ar' => 'غيني',
        ],
        [
            'country_code' => 'ER',
            'name_en' => 'Eritrea',
            'name_ar' => 'إريتريا',
            'nationality_en' => 'Eritrean',
            'nationality_ar' => 'إريتيري',
        ],
        [
            'country_code' => 'EE',
            'name_en' => 'Estonia',
            'name_ar' => 'استونيا',
            'nationality_en' => 'Estonian',
            'nationality_ar' => 'استوني',
        ],
        [
            'country_code' => 'ET',
            'name_en' => 'Ethiopia',
            'name_ar' => 'أثيوبيا',
            'nationality_en' => 'Ethiopian',
            'nationality_ar' => 'أثيوبي',
        ],
        [
            'country_code' => 'FK',
            'name_en' => 'Falkland Islands (Malvinas)',
            'name_ar' => 'جزر فوكلاند',
            'nationality_en' => 'Falkland Islander',
            'nationality_ar' => 'فوكلاندي',
        ],
        [
            'country_code' => 'FO',
            'name_en' => 'Faroe Islands',
            'name_ar' => 'جزر فارو',
            'nationality_en' => 'Faroese',
            'nationality_ar' => 'جزر فارو',
        ],
        [
            'country_code' => 'FJ',
            'name_en' => 'Fiji',
            'name_ar' => 'فيجي',
            'nationality_en' => 'Fijian',
            'nationality_ar' => 'فيجي',
        ],
        [
            'country_code' => 'FI',
            'name_en' => 'Finland',
            'name_ar' => 'فنلندا',
            'nationality_en' => 'Finnish',
            'nationality_ar' => 'فنلندي',
        ],
        [
            'country_code' => 'FR',
            'name_en' => 'France',
            'name_ar' => 'فرنسا',
            'nationality_en' => 'French',
            'nationality_ar' => 'فرنسي',
        ],
        [
            'country_code' => 'GF',
            'name_en' => 'French Guiana',
            'name_ar' => 'غويانا الفرنسية',
            'nationality_en' => 'French Guianese',
            'nationality_ar' => 'غويانا الفرنسية',
        ],
        [
            'country_code' => 'PF',
            'name_en' => 'French Polynesia',
            'name_ar' => 'بولينيزيا الفرنسية',
            'nationality_en' => 'French Polynesian',
            'nationality_ar' => 'بولينيزيي',
        ],
        [
            'country_code' => 'TF',
            'name_en' => 'French Southern and Antarctic Lands',
            'name_ar' => 'أراض فرنسية جنوبية وأنتارتيكية',
            'nationality_en' => 'French',
            'nationality_ar' => 'أراض فرنسية جنوبية وأنتارتيكية',
        ],
        [
            'country_code' => 'GA',
            'name_en' => 'Gabon',
            'name_ar' => 'الغابون',
            'nationality_en' => 'Gabonese',
            'nationality_ar' => 'غابوني',
        ],
        [
            'country_code' => 'GM',
            'name_en' => 'Gambia',
            'name_ar' => 'غامبيا',
            'nationality_en' => 'Gambian',
            'nationality_ar' => 'غامبي',
        ],
        [
            'country_code' => 'GE',
            'name_en' => 'Georgia',
            'name_ar' => 'جيورجيا',
            'nationality_en' => 'Georgian',
            'nationality_ar' => 'جيورجي',
        ],
        [
            'country_code' => 'DE',
            'name_en' => 'Germany',
            'name_ar' => 'ألمانيا',
            'nationality_en' => 'German',
            'nationality_ar' => 'ألماني',
        ],
        [
            'country_code' => 'GH',
            'name_en' => 'Ghana',
            'name_ar' => 'غانا',
            'nationality_en' => 'Ghanaian',
            'nationality_ar' => 'غاني',
        ],
        [
            'country_code' => 'GI',
            'name_en' => 'Gibraltar',
            'name_ar' => 'جبل طارق',
            'nationality_en' => 'Gibraltar',
            'nationality_ar' => 'جبل طارق',
        ],
        [
            'country_code' => 'GG',
            'name_en' => 'Guernsey',
            'name_ar' => 'غيرنزي',
            'nationality_en' => 'Guernsian',
            'nationality_ar' => 'غيرنزي',
        ],
        [
            'country_code' => 'GR',
            'name_en' => 'Greece',
            'name_ar' => 'اليونان',
            'nationality_en' => 'Greek',
            'nationality_ar' => 'يوناني',
        ],
        [
            'country_code' => 'GL',
            'name_en' => 'Greenland',
            'name_ar' => 'جرينلاند',
            'nationality_en' => 'Greenlandic',
            'nationality_ar' => 'جرينلاندي',
        ],
        [
            'country_code' => 'GD',
            'name_en' => 'Grenada',
            'name_ar' => 'غرينادا',
            'nationality_en' => 'Grenadian',
            'nationality_ar' => 'غرينادي',
        ],
        [
            'country_code' => 'GP',
            'name_en' => 'Guadeloupe',
            'name_ar' => 'جزر جوادلوب',
            'nationality_en' => 'Guadeloupe',
            'nationality_ar' => 'جزر جوادلوب',
        ],
        [
            'country_code' => 'GU',
            'name_en' => 'Guam',
            'name_ar' => 'جوام',
            'nationality_en' => 'Guamanian',
            'nationality_ar' => 'جوامي',
        ],
        [
            'country_code' => 'GT',
            'name_en' => 'Guatemala',
            'name_ar' => 'غواتيمال',
            'nationality_en' => 'Guatemalan',
            'nationality_ar' => 'غواتيمالي',
        ],
        [
            'country_code' => 'GN',
            'name_en' => 'Guinea',
            'name_ar' => 'غينيا',
            'nationality_en' => 'Guinean',
            'nationality_ar' => 'غيني',
        ],
        [
            'country_code' => 'GW',
            'name_en' => 'Guinea-Bissau',
            'name_ar' => 'غينيا-بيساو',
            'nationality_en' => 'Guinea-Bissauan',
            'nationality_ar' => 'غيني',
        ],
        [
            'country_code' => 'GY',
            'name_en' => 'Guyana',
            'name_ar' => 'غيانا',
            'nationality_en' => 'Guyanese',
            'nationality_ar' => 'غياني',
        ],
        [
            'country_code' => 'HT',
            'name_en' => 'Haiti',
            'name_ar' => 'هايتي',
            'nationality_en' => 'Haitian',
            'nationality_ar' => 'هايتي',
        ],
        [
            'country_code' => 'HM',
            'name_en' => 'Heard and Mc Donald Islands',
            'name_ar' => 'جزيرة هيرد وجزر ماكدونالد',
            'nationality_en' => 'Heard and Mc Donald Islanders',
            'nationality_ar' => 'جزيرة هيرد وجزر ماكدونالد',
        ],
        [
            'country_code' => 'HN',
            'name_en' => 'Honduras',
            'name_ar' => 'هندوراس',
            'nationality_en' => 'Honduran',
            'nationality_ar' => 'هندوراسي',
        ],
        [
            'country_code' => 'HK',
            'name_en' => 'Hong Kong',
            'name_ar' => 'هونغ كونغ',
            'nationality_en' => 'Hongkongese',
            'nationality_ar' => 'هونغ كونغي',
        ],
        [
            'country_code' => 'HU',
            'name_en' => 'Hungary',
            'name_ar' => 'المجر',
            'nationality_en' => 'Hungarian',
            'nationality_ar' => 'مجري',
        ],
        [
            'country_code' => 'IS',
            'name_en' => 'Iceland',
            'name_ar' => 'آيسلندا',
            'nationality_en' => 'Icelandic',
            'nationality_ar' => 'آيسلندي',
        ],
        [
            'country_code' => 'IN',
            'name_en' => 'India',
            'name_ar' => 'الهند',
            'nationality_en' => 'Indian',
            'nationality_ar' => 'هندي',
        ],
        [
            'country_code' => 'ID',
            'name_en' => 'Indonesia',
            'name_ar' => 'أندونيسيا',
            'nationality_en' => 'Indonesian',
            'nationality_ar' => 'أندونيسيي',
        ],
        [
            'country_code' => 'IR',
            'name_en' => 'Iran',
            'name_ar' => 'إيران',
            'nationality_en' => 'Iranian',
            'nationality_ar' => 'إيراني',
        ],
        [
            'country_code' => 'IQ',
            'name_en' => 'Iraq',
            'name_ar' => 'العراق',
            'nationality_en' => 'Iraqi',
            'nationality_ar' => 'عراقي',
        ],
        [
            'country_code' => 'IE',
            'name_en' => 'Ireland',
            'name_ar' => 'إيرلندا',
            'nationality_en' => 'Irish',
            'nationality_ar' => 'إيرلندي',
        ],
        [
            'country_code' => 'IL',
            'name_en' => 'Israel',
            'name_ar' => 'إسرائيل',
            'nationality_en' => 'Israeli',
            'nationality_ar' => 'إسرائيلي',
        ],
        [
            'country_code' => 'IT',
            'name_en' => 'Italy',
            'name_ar' => 'إيطاليا',
            'nationality_en' => 'Italian',
            'nationality_ar' => 'إيطالي',
        ],
        [
            'country_code' => 'CI',
            'name_en' => 'Ivory Coast',
            'name_ar' => 'ساحل العاج',
            'nationality_en' => 'Ivory Coastian',
            'nationality_ar' => 'ساحل العاج',
        ],
        [
            'country_code' => 'JE',
            'name_en' => 'Jersey',
            'name_ar' => 'جيرزي',
            'nationality_en' => 'Jersian',
            'nationality_ar' => 'جيرزي',
        ],
        [
            'country_code' => 'JM',
            'name_en' => 'Jamaica',
            'name_ar' => 'جمايكا',
            'nationality_en' => 'Jamaican',
            'nationality_ar' => 'جمايكي',
        ],
        [
            'country_code' => 'JP',
            'name_en' => 'Japan',
            'name_ar' => 'اليابان',
            'nationality_en' => 'Japanese',
            'nationality_ar' => 'ياباني',
        ],

        [
            'country_code' => 'KZ',
            'name_en' => 'Kazakhstan',
            'name_ar' => 'كازاخستان',
            'nationality_en' => 'Kazakh',
            'nationality_ar' => 'كازاخستاني',
        ],
        [
            'country_code' => 'KE',
            'name_en' => 'Kenya',
            'name_ar' => 'كينيا',
            'nationality_en' => 'Kenyan',
            'nationality_ar' => 'كيني',
        ],
        [
            'country_code' => 'KI',
            'name_en' => 'Kiribati',
            'name_ar' => 'كيريباتي',
            'nationality_en' => 'I-Kiribati',
            'nationality_ar' => 'كيريباتي',
        ],
        [
            'country_code' => 'KP',
            'name_en' => 'Korea(North Korea)',
            'name_ar' => 'كوريا الشمالية',
            'nationality_en' => 'North Korean',
            'nationality_ar' => 'كوري',
        ],
        [
            'country_code' => 'KR',
            'name_en' => 'Korea(South Korea)',
            'name_ar' => 'كوريا الجنوبية',
            'nationality_en' => 'South Korean',
            'nationality_ar' => 'كوري',
        ],
        [
            'country_code' => 'XK',
            'name_en' => 'Kosovo',
            'name_ar' => 'كوسوفو',
            'nationality_en' => 'Kosovar',
            'nationality_ar' => 'كوسيفي',
        ],
        [
            'country_code' => 'KW',
            'name_en' => 'Kuwait',
            'name_ar' => 'الكويت',
            'nationality_en' => 'Kuwaiti',
            'nationality_ar' => 'كويتي',
        ],
        [
            'country_code' => 'KG',
            'name_en' => 'Kyrgyzstan',
            'name_ar' => 'قيرغيزستان',
            'nationality_en' => 'Kyrgyzstani',
            'nationality_ar' => 'قيرغيزستاني',
        ],
        [
            'country_code' => 'LA',
            'name_en' => 'Lao PDR',
            'name_ar' => 'لاوس',
            'nationality_en' => 'Laotian',
            'nationality_ar' => 'لاوسي',
        ],
        [
            'country_code' => 'LV',
            'name_en' => 'Latvia',
            'name_ar' => 'لاتفيا',
            'nationality_en' => 'Latvian',
            'nationality_ar' => 'لاتيفي',
        ],
        [
            'country_code' => 'LB',
            'name_en' => 'Lebanon',
            'name_ar' => 'لبنان',
            'nationality_en' => 'Lebanese',
            'nationality_ar' => 'لبناني',
        ],
        [
            'country_code' => 'LS',
            'name_en' => 'Lesotho',
            'name_ar' => 'ليسوتو',
            'nationality_en' => 'Basotho',
            'nationality_ar' => 'ليوسيتي',
        ],
        [
            'country_code' => 'LR',
            'name_en' => 'Liberia',
            'name_ar' => 'ليبيريا',
            'nationality_en' => 'Liberian',
            'nationality_ar' => 'ليبيري',
        ],
        [
            'country_code' => 'LY',
            'name_en' => 'Libya',
            'name_ar' => 'ليبيا',
            'nationality_en' => 'Libyan',
            'nationality_ar' => 'ليبي',
        ],
        [
            'country_code' => 'LT',
            'name_en' => 'Lithuania',
            'name_ar' => 'لتوانيا',
            'nationality_en' => 'Lithuanian',
            'nationality_ar' => 'لتوانيي',
        ],
        [
            'country_code' => 'LU',
            'name_en' => 'Luxembourg',
            'name_ar' => 'لوكسمبورغ',
            'nationality_en' => 'Luxembourger',
            'nationality_ar' => 'لوكسمبورغي',
        ],
        [
            'country_code' => 'LK',
            'name_en' => 'Sri Lanka',
            'name_ar' => 'سريلانكا',
            'nationality_en' => 'Sri Lankian',
            'nationality_ar' => 'سريلانكي',
        ],
        [
            'country_code' => 'MO',
            'name_en' => 'Macau',
            'name_ar' => 'ماكاو',
            'nationality_en' => 'Macanese',
            'nationality_ar' => 'ماكاوي',
        ],
        [
            'country_code' => 'MK',
            'name_en' => 'Macedonia',
            'name_ar' => 'مقدونيا',
            'nationality_en' => 'Macedonian',
            'nationality_ar' => 'مقدوني',
        ],
        [
            'country_code' => 'MG',
            'name_en' => 'Madagascar',
            'name_ar' => 'مدغشقر',
            'nationality_en' => 'Malagasy',
            'nationality_ar' => 'مدغشقري',
        ],
        [
            'country_code' => 'MW',
            'name_en' => 'Malawi',
            'name_ar' => 'مالاوي',
            'nationality_en' => 'Malawian',
            'nationality_ar' => 'مالاوي',
        ],
        [
            'country_code' => 'MY',
            'name_en' => 'Malaysia',
            'name_ar' => 'ماليزيا',
            'nationality_en' => 'Malaysian',
            'nationality_ar' => 'ماليزي',
        ],
        [
            'country_code' => 'MV',
            'name_en' => 'Maldives',
            'name_ar' => 'المالديف',
            'nationality_en' => 'Maldivian',
            'nationality_ar' => 'مالديفي',
        ],
        [
            'country_code' => 'ML',
            'name_en' => 'Mali',
            'name_ar' => 'مالي',
            'nationality_en' => 'Malian',
            'nationality_ar' => 'مالي',
        ],
        [
            'country_code' => 'MT',
            'name_en' => 'Malta',
            'name_ar' => 'مالطا',
            'nationality_en' => 'Maltese',
            'nationality_ar' => 'مالطي',
        ],
        [
            'country_code' => 'MH',
            'name_en' => 'Marshall Islands',
            'name_ar' => 'جزر مارشال',
            'nationality_en' => 'Marshallese',
            'nationality_ar' => 'مارشالي',
        ],
        [
            'country_code' => 'MQ',
            'name_en' => 'Martinique',
            'name_ar' => 'مارتينيك',
            'nationality_en' => 'Martiniquais',
            'nationality_ar' => 'مارتينيكي',
        ],
        [
            'country_code' => 'MR',
            'name_en' => 'Mauritania',
            'name_ar' => 'موريتانيا',
            'nationality_en' => 'Mauritanian',
            'nationality_ar' => 'موريتانيي',
        ],
        [
            'country_code' => 'MU',
            'name_en' => 'Mauritius',
            'name_ar' => 'موريشيوس',
            'nationality_en' => 'Mauritian',
            'nationality_ar' => 'موريشيوسي',
        ],
        [
            'country_code' => 'YT',
            'name_en' => 'Mayotte',
            'name_ar' => 'مايوت',
            'nationality_en' => 'Mahoran',
            'nationality_ar' => 'مايوتي',
        ],
        [
            'country_code' => 'MX',
            'name_en' => 'Mexico',
            'name_ar' => 'المكسيك',
            'nationality_en' => 'Mexican',
            'nationality_ar' => 'مكسيكي',
        ],
        [
            'country_code' => 'FM',
            'name_en' => 'Micronesia',
            'name_ar' => 'مايكرونيزيا',
            'nationality_en' => 'Micronesian',
            'nationality_ar' => 'مايكرونيزيي',
        ],
        [
            'country_code' => 'MD',
            'name_en' => 'Moldova',
            'name_ar' => 'مولدافيا',
            'nationality_en' => 'Moldovan',
            'nationality_ar' => 'مولديفي',
        ],
        [
            'country_code' => 'MC',
            'name_en' => 'Monaco',
            'name_ar' => 'موناكو',
            'nationality_en' => 'Monacan',
            'nationality_ar' => 'مونيكي',
        ],
        [
            'country_code' => 'MN',
            'name_en' => 'Mongolia',
            'name_ar' => 'منغوليا',
            'nationality_en' => 'Mongolian',
            'nationality_ar' => 'منغولي',
        ],
        [
            'country_code' => 'ME',
            'name_en' => 'Montenegro',
            'name_ar' => 'الجبل الأسود',
            'nationality_en' => 'Montenegrin',
            'nationality_ar' => 'الجبل الأسود',
        ],
        [
            'country_code' => 'MS',
            'name_en' => 'Montserrat',
            'name_ar' => 'مونتسيرات',
            'nationality_en' => 'Montserratian',
            'nationality_ar' => 'مونتسيراتي',
        ],
        [
            'country_code' => 'MA',
            'name_en' => 'Morocco',
            'name_ar' => 'المغرب',
            'nationality_en' => 'Moroccan',
            'nationality_ar' => 'مغربي',
        ],
        [
            'country_code' => 'MZ',
            'name_en' => 'Mozambique',
            'name_ar' => 'موزمبيق',
            'nationality_en' => 'Mozambican',
            'nationality_ar' => 'موزمبيقي',
        ],
        [
            'country_code' => 'MM',
            'name_en' => 'Myanmar',
            'name_ar' => 'ميانمار',
            'nationality_en' => 'Myanmarian',
            'nationality_ar' => 'ميانماري',
        ],
        [
            'country_code' => 'NA',
            'name_en' => 'Namibia',
            'name_ar' => 'ناميبيا',
            'nationality_en' => 'Namibian',
            'nationality_ar' => 'ناميبي',
        ],
        [
            'country_code' => 'NR',
            'name_en' => 'Nauru',
            'name_ar' => 'نورو',
            'nationality_en' => 'Nauruan',
            'nationality_ar' => 'نوري',
        ],
        [
            'country_code' => 'NP',
            'name_en' => 'Nepal',
            'name_ar' => 'نيبال',
            'nationality_en' => 'Nepalese',
            'nationality_ar' => 'نيبالي',
        ],
        [
            'country_code' => 'NL',
            'name_en' => 'Netherlands',
            'name_ar' => 'هولندا',
            'nationality_en' => 'Dutch',
            'nationality_ar' => 'هولندي',
        ],
        [
            'country_code' => 'AN',
            'name_en' => 'Netherlands Antilles',
            'name_ar' => 'جزر الأنتيل الهولندي',
            'nationality_en' => 'Dutch Antilier',
            'nationality_ar' => 'هولندي',
        ],
        [
            'country_code' => 'NC',
            'name_en' => 'New Caledonia',
            'name_ar' => 'كاليدونيا الجديدة',
            'nationality_en' => 'New Caledonian',
            'nationality_ar' => 'كاليدوني',
        ],
        [
            'country_code' => 'NZ',
            'name_en' => 'New Zealand',
            'name_ar' => 'نيوزيلندا',
            'nationality_en' => 'New Zealander',
            'nationality_ar' => 'نيوزيلندي',
        ],
        [
            'country_code' => 'NI',
            'name_en' => 'Nicaragua',
            'name_ar' => 'نيكاراجوا',
            'nationality_en' => 'Nicaraguan',
            'nationality_ar' => 'نيكاراجوي',
        ],
        [
            'country_code' => 'NE',
            'name_en' => 'Niger',
            'name_ar' => 'النيجر',
            'nationality_en' => 'Nigerien',
            'nationality_ar' => 'نيجيري',
        ],
        [
            'country_code' => 'NG',
            'name_en' => 'Nigeria',
            'name_ar' => 'نيجيريا',
            'nationality_en' => 'Nigerian',
            'nationality_ar' => 'نيجيري',
        ],
        [
            'country_code' => 'NU',
            'name_en' => 'Niue',
            'name_ar' => 'ني',
            'nationality_en' => 'Niuean',
            'nationality_ar' => 'ني',
        ],
        [
            'country_code' => 'NF',
            'name_en' => 'Norfolk Island',
            'name_ar' => 'جزيرة نورفولك',
            'nationality_en' => 'Norfolk Islander',
            'nationality_ar' => 'نورفوليكي',
        ],
        [
            'country_code' => 'MP',
            'name_en' => 'Northern Mariana Islands',
            'name_ar' => 'جزر ماريانا الشمالية',
            'nationality_en' => 'Northern Marianan',
            'nationality_ar' => 'ماريني',
        ],
        [
            'country_code' => 'NO',
            'name_en' => 'Norway',
            'name_ar' => 'النرويج',
            'nationality_en' => 'Norwegian',
            'nationality_ar' => 'نرويجي',
        ],
        [
            'country_code' => 'OM',
            'name_en' => 'Oman',
            'name_ar' => 'عمان',
            'nationality_en' => 'Omani',
            'nationality_ar' => 'عماني',
        ],
        [
            'country_code' => 'PK',
            'name_en' => 'Pakistan',
            'name_ar' => 'باكستان',
            'nationality_en' => 'Pakistani',
            'nationality_ar' => 'باكستاني',
        ],
        [
            'country_code' => 'PW',
            'name_en' => 'Palau',
            'name_ar' => 'بالاو',
            'nationality_en' => 'Palauan',
            'nationality_ar' => 'بالاوي',
        ],
        [
            'country_code' => 'PS',
            'name_en' => 'Palestine',
            'name_ar' => 'فلسطين',
            'nationality_en' => 'Palestinian',
            'nationality_ar' => 'فلسطيني',
        ],
        [
            'country_code' => 'PA',
            'name_en' => 'Panama',
            'name_ar' => 'بنما',
            'nationality_en' => 'Panamanian',
            'nationality_ar' => 'بنمي',
        ],
        [
            'country_code' => 'PG',
            'name_en' => 'Papua New Guinea',
            'name_ar' => 'بابوا غينيا الجديدة',
            'nationality_en' => 'Papua New Guinean',
            'nationality_ar' => 'بابوي',
        ],
        [
            'country_code' => 'PY',
            'name_en' => 'Paraguay',
            'name_ar' => 'باراغواي',
            'nationality_en' => 'Paraguayan',
            'nationality_ar' => 'بارغاوي',
        ],
        [
            'country_code' => 'PE',
            'name_en' => 'Peru',
            'name_ar' => 'بيرو',
            'nationality_en' => 'Peruvian',
            'nationality_ar' => 'بيري',
        ],
        [
            'country_code' => 'PH',
            'name_en' => 'Philippines',
            'name_ar' => 'الفليبين',
            'nationality_en' => 'Filipino',
            'nationality_ar' => 'فلبيني',
        ],
        [
            'country_code' => 'PN',
            'name_en' => 'Pitcairn',
            'name_ar' => 'بيتكيرن',
            'nationality_en' => 'Pitcairn Islander',
            'nationality_ar' => 'بيتكيرني',
        ],
        [
            'country_code' => 'PL',
            'name_en' => 'Poland',
            'name_ar' => 'بولونيا',
            'nationality_en' => 'Polish',
            'nationality_ar' => 'بوليني',
        ],
        [
            'country_code' => 'PT',
            'name_en' => 'Portugal',
            'name_ar' => 'البرتغال',
            'nationality_en' => 'Portuguese',
            'nationality_ar' => 'برتغالي',
        ],
        [
            'country_code' => 'PR',
            'name_en' => 'Puerto Rico',
            'name_ar' => 'بورتو ريكو',
            'nationality_en' => 'Puerto Rican',
            'nationality_ar' => 'بورتي',
        ],
        [
            'country_code' => 'QA',
            'name_en' => 'Qatar',
            'name_ar' => 'قطر',
            'nationality_en' => 'Qatari',
            'nationality_ar' => 'قطري',
        ],
        [
            'country_code' => 'RE',
            'name_en' => 'Reunion Island',
            'name_ar' => 'ريونيون',
            'nationality_en' => 'Reunionese',
            'nationality_ar' => 'ريونيوني',
        ],
        [
            'country_code' => 'RO',
            'name_en' => 'Romania',
            'name_ar' => 'رومانيا',
            'nationality_en' => 'Romanian',
            'nationality_ar' => 'روماني',
        ],
        [
            'country_code' => 'RU',
            'name_en' => 'Russian',
            'name_ar' => 'روسيا',
            'nationality_en' => 'Russian',
            'nationality_ar' => 'روسي',
        ],
        [
            'country_code' => 'RW',
            'name_en' => 'Rwanda',
            'name_ar' => 'رواندا',
            'nationality_en' => 'Rwandan',
            'nationality_ar' => 'رواندا',
        ],
        [
            'country_code' => 'KN',
            'name_en' => 'Saint Kitts and Nevis',
            'name_ar' => 'سانت كيتس ونيفس,',
            'nationality_en' => 'Kittitian/Nevisian',
            'nationality_ar' => 'سانت كيتس ونيفس',
        ],
        [
            'country_code' => 'MF',
            'name_en' => 'Saint Martin (French part)',
            'name_ar' => 'ساينت مارتن فرنسي',
            'nationality_en' => 'St. Martian(French)',
            'nationality_ar' => 'ساينت مارتني فرنسي',
        ],
        [
            'country_code' => 'SX',
            'name_en' => 'Sint Maarten (Dutch part)',
            'name_ar' => 'ساينت مارتن هولندي',
            'nationality_en' => 'St. Martian(Dutch)',
            'nationality_ar' => 'ساينت مارتني هولندي',
        ],
        [
            'country_code' => 'LC',
            'name_en' => 'Saint Pierre and Miquelon',
            'name_ar' => 'سان بيير وميكلون',
            'nationality_en' => 'St. Pierre and Miquelon',
            'nationality_ar' => 'سان بيير وميكلوني',
        ],
        [
            'country_code' => 'VC',
            'name_en' => 'Saint Vincent and the Grenadines',
            'name_ar' => 'سانت فنسنت وجزر غرينادين',
            'nationality_en' => 'Saint Vincent and the Grenadines',
            'nationality_ar' => 'سانت فنسنت وجزر غرينادين',
        ],
        [
            'country_code' => 'WS',
            'name_en' => 'Samoa',
            'name_ar' => 'ساموا',
            'nationality_en' => 'Samoan',
            'nationality_ar' => 'ساموي',
        ],
        [
            'country_code' => 'SM',
            'name_en' => 'San Marino',
            'name_ar' => 'سان مارينو',
            'nationality_en' => 'Sammarinese',
            'nationality_ar' => 'ماريني',
        ],
        [
            'country_code' => 'ST',
            'name_en' => 'Sao Tome and Principe',
            'name_ar' => 'ساو تومي وبرينسيبي',
            'nationality_en' => 'Sao Tomean',
            'nationality_ar' => 'ساو تومي وبرينسيبي',
        ],
        [
            'country_code' => 'SA',
            'name_en' => 'Saudi Arabia',
            'name_ar' => 'المملكة العربية السعودية',
            'nationality_en' => 'Saudi Arabian',
            'nationality_ar' => 'سعودي',
        ],
        [
            'country_code' => 'SN',
            'name_en' => 'Senegal',
            'name_ar' => 'السنغال',
            'nationality_en' => 'Senegalese',
            'nationality_ar' => 'سنغالي',
        ],
        [
            'country_code' => 'RS',
            'name_en' => 'Serbia',
            'name_ar' => 'صربيا',
            'nationality_en' => 'Serbian',
            'nationality_ar' => 'صربي',
        ],
        [
            'country_code' => 'SC',
            'name_en' => 'Seychelles',
            'name_ar' => 'سيشيل',
            'nationality_en' => 'Seychellois',
            'nationality_ar' => 'سيشيلي',
        ],
        [
            'country_code' => 'SL',
            'name_en' => 'Sierra Leone',
            'name_ar' => 'سيراليون',
            'nationality_en' => 'Sierra Leonean',
            'nationality_ar' => 'سيراليوني',
        ],
        [
            'country_code' => 'SG',
            'name_en' => 'Singapore',
            'name_ar' => 'سنغافورة',
            'nationality_en' => 'Singaporean',
            'nationality_ar' => 'سنغافوري',
        ],
        [
            'country_code' => 'SK',
            'name_en' => 'Slovakia',
            'name_ar' => 'سلوفاكيا',
            'nationality_en' => 'Slovak',
            'nationality_ar' => 'سولفاكي',
        ],
        [
            'country_code' => 'SI',
            'name_en' => 'Slovenia',
            'name_ar' => 'سلوفينيا',
            'nationality_en' => 'Slovenian',
            'nationality_ar' => 'سولفيني',
        ],
        [
            'country_code' => 'SB',
            'name_en' => 'Solomon Islands',
            'name_ar' => 'جزر سليمان',
            'nationality_en' => 'Solomon Island',
            'nationality_ar' => 'جزر سليمان',
        ],
        [
            'country_code' => 'SO',
            'name_en' => 'Somalia',
            'name_ar' => 'الصومال',
            'nationality_en' => 'Somali',
            'nationality_ar' => 'صومالي',
        ],
        [
            'country_code' => 'ZA',
            'name_en' => 'South Africa',
            'name_ar' => 'جنوب أفريقيا',
            'nationality_en' => 'South African',
            'nationality_ar' => 'أفريقي',
        ],
        [
            'country_code' => 'GS',
            'name_en' => 'South Georgia and the South Sandwich',
            'name_ar' => 'المنطقة القطبية الجنوبية',
            'nationality_en' => 'South Georgia and the South Sandwich',
            'nationality_ar' => 'لمنطقة القطبية الجنوبية',
        ],
        [
            'country_code' => 'SS',
            'name_en' => 'South Sudan',
            'name_ar' => 'السودان الجنوبي',
            'nationality_en' => 'South Sudanese',
            'nationality_ar' => 'سوادني جنوبي',
        ],
        [
            'country_code' => 'ES',
            'name_en' => 'Spain',
            'name_ar' => 'إسبانيا',
            'nationality_en' => 'Spanish',
            'nationality_ar' => 'إسباني',
        ],
        [
            'country_code' => 'SH',
            'name_en' => 'Saint Helena',
            'name_ar' => 'سانت هيلانة',
            'nationality_en' => 'St. Helenian',
            'nationality_ar' => 'هيلاني',
        ],
        [
            'country_code' => 'SD',
            'name_en' => 'Sudan',
            'name_ar' => 'السودان',
            'nationality_en' => 'Sudanese',
            'nationality_ar' => 'سوداني',
        ],
        [
            'country_code' => 'SR',
            'name_en' => 'Suriname',
            'name_ar' => 'سورينام',
            'nationality_en' => 'Surinamese',
            'nationality_ar' => 'سورينامي',
        ],
        [
            'country_code' => 'SJ',
            'name_en' => 'Svalbard and Jan Mayen',
            'name_ar' => 'سفالبارد ويان ماين',
            'nationality_en' => 'Svalbardian/Jan Mayenian',
            'nationality_ar' => 'سفالبارد ويان ماين',
        ],
        [
            'country_code' => 'SZ',
            'name_en' => 'Swaziland',
            'name_ar' => 'سوازيلند',
            'nationality_en' => 'Swazi',
            'nationality_ar' => 'سوازيلندي',
        ],
        [
            'country_code' => 'SE',
            'name_en' => 'Sweden',
            'name_ar' => 'السويد',
            'nationality_en' => 'Swedish',
            'nationality_ar' => 'سويدي',
        ],
        [
            'country_code' => 'CH',
            'name_en' => 'Switzerland',
            'name_ar' => 'سويسرا',
            'nationality_en' => 'Swiss',
            'nationality_ar' => 'سويسري',
        ],
        [
            'country_code' => 'SY',
            'name_en' => 'Syria',
            'name_ar' => 'سوريا',
            'nationality_en' => 'Syrian',
            'nationality_ar' => 'سوري',
        ],
        [
            'country_code' => 'TW',
            'name_en' => 'Taiwan',
            'name_ar' => 'تايوان',
            'nationality_en' => 'Taiwanese',
            'nationality_ar' => 'تايواني',
        ],
        [
            'country_code' => 'TJ',
            'name_en' => 'Tajikistan',
            'name_ar' => 'طاجيكستان',
            'nationality_en' => 'Tajikistani',
            'nationality_ar' => 'طاجيكستاني',
        ],
        [
            'country_code' => 'TZ',
            'name_en' => 'Tanzania',
            'name_ar' => 'تنزانيا',
            'nationality_en' => 'Tanzanian',
            'nationality_ar' => 'تنزانيي',
        ],
        [
            'country_code' => 'TH',
            'name_en' => 'Thailand',
            'name_ar' => 'تايلندا',
            'nationality_en' => 'Thai',
            'nationality_ar' => 'تايلندي',
        ],
        [
            'country_code' => 'TL',
            'name_en' => 'Timor-Leste',
            'name_ar' => 'تيمور الشرقية',
            'nationality_en' => 'Timor-Lestian',
            'nationality_ar' => 'تيموري',
        ],
        [
            'country_code' => 'TG',
            'name_en' => 'Togo',
            'name_ar' => 'توغو',
            'nationality_en' => 'Togolese',
            'nationality_ar' => 'توغي',
        ],
        [
            'country_code' => 'TK',
            'name_en' => 'Tokelau',
            'name_ar' => 'توكيلاو',
            'nationality_en' => 'Tokelaian',
            'nationality_ar' => 'توكيلاوي',
        ],
        [
            'country_code' => 'TO',
            'name_en' => 'Tonga',
            'name_ar' => 'تونغا',
            'nationality_en' => 'Tongan',
            'nationality_ar' => 'تونغي',
        ],
        [
            'country_code' => 'TT',
            'name_en' => 'Trinidad and Tobago',
            'name_ar' => 'ترينيداد وتوباغو',
            'nationality_en' => 'Trinidadian/Tobagonian',
            'nationality_ar' => 'ترينيداد وتوباغو',
        ],
        [
            'country_code' => 'TN',
            'name_en' => 'Tunisia',
            'name_ar' => 'تونس',
            'nationality_en' => 'Tunisian',
            'nationality_ar' => 'تونسي',
        ],
        [
            'country_code' => 'TR',
            'name_en' => 'Turkey',
            'name_ar' => 'تركيا',
            'nationality_en' => 'Turkish',
            'nationality_ar' => 'تركي',
        ],
        [
            'country_code' => 'TM',
            'name_en' => 'Turkmenistan',
            'name_ar' => 'تركمانستان',
            'nationality_en' => 'Turkmen',
            'nationality_ar' => 'تركمانستاني',
        ],
        [
            'country_code' => 'TC',
            'name_en' => 'Turks and Caicos Islands',
            'name_ar' => 'جزر توركس وكايكوس',
            'nationality_en' => 'Turks and Caicos Islands',
            'nationality_ar' => 'جزر توركس وكايكوس',
        ],
        [
            'country_code' => 'TV',
            'name_en' => 'Tuvalu',
            'name_ar' => 'توفالو',
            'nationality_en' => 'Tuvaluan',
            'nationality_ar' => 'توفالي',
        ],
        [
            'country_code' => 'UG',
            'name_en' => 'Uganda',
            'name_ar' => 'أوغندا',
            'nationality_en' => 'Ugandan',
            'nationality_ar' => 'أوغندي',
        ],
        [
            'country_code' => 'UA',
            'name_en' => 'Ukraine',
            'name_ar' => 'أوكرانيا',
            'nationality_en' => 'Ukrainian',
            'nationality_ar' => 'أوكراني',
        ],
        [
            'country_code' => 'AE',
            'name_en' => 'United Arab Emirates',
            'name_ar' => 'الإمارات العربية المتحدة',
            'nationality_en' => 'Emirati',
            'nationality_ar' => 'إماراتي',
        ],
        [
            'country_code' => 'GB',
            'name_en' => 'United Kingdom',
            'name_ar' => 'المملكة المتحدة',
            'nationality_en' => 'British',
            'nationality_ar' => 'بريطاني',
        ],
        [
            'country_code' => 'US',
            'name_en' => 'United States',
            'name_ar' => 'الولايات المتحدة',
            'nationality_en' => 'American',
            'nationality_ar' => 'أمريكي',
        ],
        [
            'country_code' => 'UM',
            'name_en' => 'US Minor Outlying Islands',
            'name_ar' => 'قائمة الولايات والمناطق الأمريكية',
            'nationality_en' => 'US Minor Outlying Islander',
            'nationality_ar' => 'أمريكي',
        ],
        [
            'country_code' => 'UY',
            'name_en' => 'Uruguay',
            'name_ar' => 'أورغواي',
            'nationality_en' => 'Uruguayan',
            'nationality_ar' => 'أورغواي',
        ],
        [
            'country_code' => 'UZ',
            'name_en' => 'Uzbekistan',
            'name_ar' => 'أوزباكستان',
            'nationality_en' => 'Uzbek',
            'nationality_ar' => 'أوزباكستاني',
        ],
        [
            'country_code' => 'VU',
            'name_en' => 'Vanuatu',
            'name_ar' => 'فانواتو',
            'nationality_en' => 'Vanuatuan',
            'nationality_ar' => 'فانواتي',
        ],
        [
            'country_code' => 'VE',
            'name_en' => 'Venezuela',
            'name_ar' => 'فنزويلا',
            'nationality_en' => 'Venezuelan',
            'nationality_ar' => 'فنزويلي',
        ],
        [
            'country_code' => 'VN',
            'name_en' => 'Vietnam',
            'name_ar' => 'فيتنام',
            'nationality_en' => 'Vietnamese',
            'nationality_ar' => 'فيتنامي',
        ],
        [
            'country_code' => 'VI',
            'name_en' => 'Virgin Islands (U.S.)',
            'name_ar' => 'الجزر العذراء الأمريكي',
            'nationality_en' => 'American Virgin Islander',
            'nationality_ar' => 'أمريكي',
        ],
        [
            'country_code' => 'VA',
            'name_en' => 'Vatican City',
            'name_ar' => 'فنزويلا',
            'nationality_en' => 'Vatican',
            'nationality_ar' => 'فاتيكاني',
        ],
        [
            'country_code' => 'WF',
            'name_en' => 'Wallis and Futuna Islands',
            'name_ar' => 'والس وفوتونا',
            'nationality_en' => 'Wallisian/Futunan',
            'nationality_ar' => 'فوتوني',
        ],
        [
            'country_code' => 'EH',
            'name_en' => 'Western Sahara',
            'name_ar' => 'الصحراء الغربية',
            'nationality_en' => 'Sahrawian',
            'nationality_ar' => 'صحراوي',
        ],
        [
            'country_code' => 'YE',
            'name_en' => 'Yemen',
            'name_ar' => 'اليمن',
            'nationality_en' => 'Yemeni',
            'nationality_ar' => 'يمني',
        ],
        [
            'country_code' => 'ZM',
            'name_en' => 'Zambia',
            'name_ar' => 'زامبيا',
            'nationality_en' => 'Zambian',
            'nationality_ar' => 'زامبياني',
        ],
        [
            'country_code' => 'ZW',
            'name_en' => 'Zimbabwe',
            'name_ar' => 'زمبابوي',
            'nationality_en' => 'Zimbabwean',
            'nationality_ar' => 'زمبابوي',
        ],


    ];
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%countries}}', [
            'id' => $this->primaryKey(),
            'country_code' => $this->string(5)->defaultValue(null),
            'name_en' => $this->string()->notNull(),
            'name_ar' => $this->string()->notNull(),
            'nationality_en' => $this->string()->defaultValue(null),
            'nationality_ar' => $this->string()->defaultValue(null),
            'created_at' => $this->dateTime()->defaultValue(null),
            'updated_at' => $this->dateTime()->defaultValue(null),
        ], $tableOptions);

        Yii::$app->db
            ->createCommand()
            ->batchInsert(
                'countries',
                [
                    'country_code',
                    'name_en',
                    'name_ar',
                    'nationality_en',
                    'nationality_ar'
                ],
                $this->countries
            )
            ->execute();
    }

    public function down()
    {
        $this->dropTable('{{%countries}}');
    }
}
